ModelFilepath = "E:\OneDrive\OneDrive - De La Salle University - Manila\000 Coral' yan!\00 Pipeline\corallian-segmentation-pipeline\models\coral_segmentation.pth"

[inference]
InputRoot = "E:\DLSU\[PC] Coral 'yan!\data\ORIGINAL (aka MONITORING)\2024 (COMPLETE)"
OutputRoot = "E:\DLSU\[PC] Coral 'yan!\data\SEGMENTED-CORALS-NOT-CROPPED"
ImageSize = 512

[training]
DoTraining = true
TrainImageDir = "E:/DLSU/[PC] Coral 'yan!/data/MASKED-CORALS/CoralMask/train/images"
TrainMaskDir = "E:/DLSU/[PC] Coral 'yan!/data/MASKED-CORALS/CoralMask/train/output_masks"
ValImageDir = "E:/DLSU/[PC] Coral 'yan!/data/MASKED-CORALS/CoralMask/test/images"
ValMaskDir = "E:/DLSU/[PC] Coral 'yan!/data/MASKED-CORALS/CoralMask/test/output_masks"
BatchSize = 8
LearningRate = 0.0001
NumEpochs = 50

[resnet]
ResNetModel = 18

[aspp]
ASPPEnabled = true
ASPPInChannels = 512
ASPPOutChannels = 256
AtrousRates = [6, 12, 18]

[duc]
DUCEnabled = true
DUCUpFactor = 2

[model]
NumClasses = 1
